CREATE TABLE IF NOT EXISTS Semestru (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Numar INT NOT NULL CHECK (Numar IN (1, 2))
);

CREATE TABLE IF NOT EXISTS Curs (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AreDistribuita BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Laborator (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NotaProiect REAL NULL,
    PondereProiect INT NOT NULL CHECK (PondereProiect BETWEEN 0 AND 100),
    NotaSeminar REAL NULL,
    PondereSeminar INT NOT NULL DEFAULT 0 CHECK (PondereSeminar BETWEEN 0 AND 100)
);

CREATE TABLE IF NOT EXISTS Materie (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Nume TEXT NOT NULL,
    NumarCredite INT NOT NULL CHECK (NumarCredite BETWEEN 1 AND 30),
    PondereCurs INT NOT NULL CHECK (PondereCurs BETWEEN 0 AND 100),
    SemestruID INT NOT NULL,
    CursId INT NOT NULL,
    LaboratorId INT NULL,
    FOREIGN KEY (SemestruID) REFERENCES Semestru(ID),
    FOREIGN KEY (CursId) REFERENCES Curs(ID),
    FOREIGN KEY (LaboratorId) REFERENCES Laborator(ID)
);

CREATE TABLE IF NOT EXISTS Distribuita (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CursId INT NOT NULL,
    NumarEvaluare INT NOT NULL,
    Nota REAL NULL,
    FOREIGN KEY (CursId) REFERENCES Curs(ID)
);

CREATE TABLE IF NOT EXISTS NotaLaborator (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LaboratorId INT NOT NULL,
    Nota REAL NULL,
    FOREIGN KEY (LaboratorId) REFERENCES Laborator(ID)
);